### ISSUE TITLE
21 - function junction - js practice

### ISSUE THREAD

**Issue by MatthewSDick** [MatthewSDick/assignments#26]
# JavaScript practice

Using JavaScript takes practice and the best practice is repetition. This exercise allow you time to work on the basics of JavaScript and how to apply that logic to solving problems.

## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/function-junction) to your own account.
2. Change into your projects directory:
3. Clone your repository: `hub clone function-junction`
4. Change into your project's directory: `cd function-junction``
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor
7. Start the test runner: `yarn test`
8. Open `src/functions.test.js` and work on functions until tests pass.
9. Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

## Explorer Mode

- Work on `function-junction` using the directions above
- Finish the code and have all tests passing
- Have no linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Adventure Mode

- Do the same with the Function-Junction Koans at [https://github.com/suncoast-devs/js-iteration](https://github.com/suncoast-devs/js-iteration)

- Do the same with the JavaScript Koans at [https://github.com/suncoast-devs/koans/blob/master/koans.js](https://github.com/suncoast-devs/koans/blob/master/koans.js)

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by MatthewSDick** [comment]
Explorer - https://github.com/MatthewSDick/function-junction

Adventure - https://github.com/MatthewSDick/js-iteration

*** I would like to finish the last 2 in Adventure if you can help ***

After the success of  mapYourself and when trying filterYourself I am getting the below error.  
If I take out code for filterYourself and put back in the // ... close VS and open again it scans thru mapYourself.  When I code filterYourself even with a empty function it fails again.

 ✖ Internal error when running src/functions.test.js
  UnsupportedError: Plugin does not support this version of Concordance
  UnsupportedError: Plugin does not support this version of Concordance
      at verify (/Users/matthewdick/cohort-17/js-iteration/node_modules/concordance/lib/pluginRegistry.js:87:13)
      at add (/Users/matthewdick/cohort-17/js-iteration/node_modules/concordance/lib/pluginRegistry.js:129:3)
      at /Users/matthewdick/cohort-17/js-iteration/node_modules/concordance/lib/pluginRegistry.js:206:32
      at Array.map (<anonymous>)
      at Object.getTryDescribeValues (/Users/matthewdick/cohort-17/js-iteration/node_modules/concordance/lib/pluginRegistry.js:206:18)
      at registerPlugins (/Users/matthewdick/cohort-17/js-iteration/node_modules/concordance/lib/describe.js:88:33)
      at describe (/Users/matthewdick/cohort-17/js-iteration/node_modules/concordance/lib/describe.js:141:22)
      at Object.format (/Users/matthewdick/cohort-17/js-iteration/node_modules/concordance/lib/format.js:99:27)
      at formatErrorValue (/Users/matthewdick/cohort-17/js-iteration/node_modules/ava/lib/test.js:13:32)
      at Test.run (/Users/matthewdick/cohort-17/js-iteration/node_modules/ava/lib/test.js:571:15)



  `--fail-fast` is on. At least 3 tests were skipped, as well as 1 test file.

  Type `r` and press enter to rerun tests
  Type `u` and press enter to update snapshots
